### ISSUE TITLE
Setting up System-Location / SNMP-Location

### ISSUE THREAD

**Issue by fre4ki** [PowerAruba/PowerArubaCX#55]
Hi Alexis,

can you tell me how to change the system-location / snmp-location?

It is defined in >> ArubaCXSystem/other_config

But i found no options so far.

Thank you!

Andy

**Comment by alagoutte** [comment]
Hi Andy,

Yes, it is not (yet) supported but you can use -use_pipeline parameter (and add info because not available by default)

```powershell
$system = (Get-ArubaCXSystem -selector writable) 
$system.other_config |  Add-member -name "system_contact" -membertype NoteProperty -Value "PowerArubaCX"
$system | Set-ArubaCXSystem -use_pipeline
```

i can look for add on next release, do you need some other stuff ?

**Comment by fre4ki** [comment]
**It have to be system_location, but it works:**

```powershell
$system = (Get-ArubaCXSystem -selector writable) 
$system.other_config |  Add-member -name "**system_location**" -membertype NoteProperty -Value "PowerArubaCX"
$system | Set-ArubaCXSystem -use_pipeline
```
Really thanks for your support.

Andy

**Comment by alagoutte** [comment]
Thanks for quick return and it is work with system_location and system_description, i will look to add to have directly option on _Set-ArubaCXSystem_
