### ISSUE TITLE
Include credentials in scripts

### ISSUE THREAD

**Issue by fre4ki** [PowerAruba/PowerArubaCX#56]
Hey Alexis,

how can i include the credentials? I tried it with the powershell integrated prompts gut it will not work..

Is there a way to integrate it?

**Comment by alagoutte** [comment]
Hi,

You can use

```powershell
$mysecpassword = ConvertTo-SecureString aruba -AsPlainText -Force
Connect-ArubaCX -Server 192.0.2.1 -Username admin -Password $mysecpassword
```

**Comment by fre4ki** [comment]
Amazing, it works! Thank you!
