### ISSUE TITLE
no login possible with firmware 10.12

### ISSUE THREAD

**Issue by danielahuberx** [PowerAruba/PowerArubaCX#67]
we have an aos-cx switch wiith firmware version 10.12

After entering credentials for the Connect-ArubaCW command we get presented with the output that firmware
has to be >= 10.06

Switch is running on firmware 10.12

**Comment by alagoutte** [comment]
Hi daniel,

Strange, i tested with 10.12 and work for me

What the switch model (and firmware)

can you post the output with _connect-ArubaCX -SkipCertificateCheck -Verbose_ ?

**Comment by danielahuberx** [comment]
Hi Alexis,

this is the output:
(the black bar hides the ip address)
***@***.***


Switch model: 6100 24G CL4 4SFP+ Swch (JL677A)
Firmware: 10.12.0006
Type: AOS-CX

Daniela


Von: Alexis La Goutte ***@***.***>
Gesendet: Dienstag, 13. Februar 2024 15:49
An: PowerAruba/PowerArubaCX ***@***.***>
Cc: Daniela Huber, NET-Solutions ***@***.***>; Author ***@***.***>
Betreff: Re: [PowerAruba/PowerArubaCX] no login possible with firmware 10.12 (Issue #67)


Hi daniel,

Strange, i tested with 10.12 and work for me

What the switch model (and firmware)

can you post the output with connect-ArubaCX -SkipCertificateCheck -Verbose ?

**Comment by alagoutte** [comment]
> (the black bar hides the ip address) ***@***.***

You have attach a screenshot ? (i don't pass on github)

**Comment by danielahuberx** [comment]
![screenshot_arubacx](https://github.com/PowerAruba/PowerArubaCX/assets/159922787/60a81f6b-6253-47ff-947a-32c8555d61e3)


I pasted it again directly on github - can you see it now?

**Comment by alagoutte** [comment]
You need to use port 443 ;-) we are using API not SSH !

**Comment by danielahuberx** [comment]
Of course! You're absolutely right. Sorry, my bad!
I guess old habits just die hard :)
Thanks for the quick replies!
