### ISSUE TITLE
Version for ARUBA OS CX 10.13.XX

### ISSUE THREAD

**Issue by luanoprzybilski** [PowerAruba/PowerArubaCX#69]
it is not possible to use the modules from software 10.13.0010

![image](https://github.com/PowerAruba/PowerArubaCX/assets/152485034/f86e5676-2fa5-4dd9-ac60-3eed75ec79d2)

**Comment by alagoutte** [comment]
do you have use with -skipcertificatecheck ?

**Comment by alagoutte** [comment]
Hi,

It is good ?

**Comment by rEs-84** [comment]
I have a issue on one machine where your module doesnt work to connect to any of our switches.
![Image](https://github.com/user-attachments/assets/7267cdc5-36b6-4c4c-aa0e-bd5ee848eaab)

is there anything in particular that stops it from connecting?
Tried powerhsell 5.1 and 7.5.1
Tried ISE and Visual Studio Code

the machine is fine in edge

![Image](https://github.com/user-attachments/assets/2a00d3d5-fd79-4553-82e0-34df11a4b5ed)

other machines are fine

![Image](https://github.com/user-attachments/assets/04a6e3b7-07ec-4aa7-ba1b-8c07ca593bb2)

![Image](https://github.com/user-attachments/assets/b62e9f60-18d5-4731-9dc9-53ff2c157587)

![Image](https://github.com/user-attachments/assets/68504cd4-1638-4346-9e91-8dedadf7914a)

Thanks in advance

**Comment by alagoutte** [comment]
What version of powershell don't work ? do you have add -SkipCertificateCheck ?

May be reopen an issue ?
